// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV8bh9kwJoplLF18VjPClt94DMAjCf3gQ',
    appId: '1:277948496877:web:3bfc57d48726f4603b05e4',
    messagingSenderId: '277948496877',
    projectId: 'kma-analys-a91b4',
    authDomain: 'kma-analys-a91b4.firebaseapp.com',
    storageBucket: 'kma-analys-a91b4.appspot.com',
    measurementId: 'G-74CS1KWPZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVnAM6c3QfneGVen4BPnpfIV5s6ICoYpU',
    appId: '1:277948496877:android:bec06a04c6ebf9de3b05e4',
    messagingSenderId: '277948496877',
    projectId: 'kma-analys-a91b4',
    storageBucket: 'kma-analys-a91b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjzjFbAOu-rTjgdqG7nSqAGRxyI127V7Q',
    appId: '1:277948496877:ios:535a3e5ec046e3fa3b05e4',
    messagingSenderId: '277948496877',
    projectId: 'kma-analys-a91b4',
    storageBucket: 'kma-analys-a91b4.appspot.com',
    iosClientId: '277948496877-1n93d0tfmo8vk3bprat57j93fdrcf774.apps.googleusercontent.com',
    iosBundleId: 'com.example.kmaanalys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjzjFbAOu-rTjgdqG7nSqAGRxyI127V7Q',
    appId: '1:277948496877:ios:80bfe760427c81b43b05e4',
    messagingSenderId: '277948496877',
    projectId: 'kma-analys-a91b4',
    storageBucket: 'kma-analys-a91b4.appspot.com',
    iosClientId: '277948496877-44bugu9lpqm19iorm0c1fpv5cou1iqjc.apps.googleusercontent.com',
    iosBundleId: 'com.sfaholding.kmaanalys',
  );
}
